---
#title: "COP20 Approval Memo"
#date: "`r paste0('Generated on ' , format(Sys.time(), '%Y-%m-%d'))`"
output:
  pdf_document:
    toc: no
    latex_engine: xelatex
  html_document:
    toc: no
    df_print: paged
header-includes:
- \usepackage{tabularx,booktabs}
- \usepackage{multirow}
- \usepackage{float}
- \usepackage{xcolor}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{fancyhdr}
mainfont: FreeSans
geometry: margin=1.5cm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(kableExtra.latex.load_packages = FALSE)
```

\addtolength{\headheight}{0.1cm}
\pagestyle{fancyplain}
```{r header_name ,results='asis', echo=FALSE}
ou_name<-getOrgtunitNamefromUID(input$ou, d2_session = user_input$d2_session)
cat(paste("\\rhead{Operating Unit: ",ou_name," }"))
cat(paste("\\lhead{Date: ",format(Sys.time(), '%Y-%m-%d'),"}"))
```
\renewcommand{\headrulewidth}{0pt}
\setlength\aboverulesep{0pt}
\setlength\belowrulesep{0pt}

```{r prio_table ,results='asis', echo=FALSE}
if (!exists("d")) {
  d <- memo_data()
}

#Format each cell
total_rows_bg<- ifelse( d$prio$Age ==  "Total",
                     "#E4DFEC","#FFFFFF")

total_rows_bold<-ifelse( d$prio$Age ==  "Total", TRUE,FALSE)

#Transform all zeros to dashes
 d$prio %<>% 
  dplyr::mutate_if(is.numeric, function(x) ifelse(x == 0 ,"-",formatC(x, format="f", big.mark=",",digits = 0))) 

 above_header_df<-data.frame(header_names=c(ou_name,"SNU Prioritizations"),colspan=c(2,7),stringsAsFactors = FALSE)

kable(d$prio, "latex", 
      booktabs = T,
      longtable = T,caption = "Prioritization Table") %>%
  add_header_above(header=above_header_df,background ="#CCC0D9", bold = TRUE ) %>%
  row_spec(row=0,background ="#CCC0D9",hline_after = TRUE, bold = TRUE) %>% 
  column_spec(1,width = "1.2in",bold=TRUE, background = 'white',border_left = TRUE,border_right = TRUE) %>%
  column_spec(2,width = "0.25in", background = total_rows_bg, bold = total_rows_bold, border_right = TRUE) %>% 
  column_spec(3:8, width = "0.6in", background = total_rows_bg, bold=total_rows_bold) %>% 
  column_spec(9, width = "0.6in", background = total_rows_bg, bold=total_rows_bold, border_left = TRUE, border_right = TRUE) %>% 
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle") %>% 
  kable_styling(font_size = 8) %>% 
    add_footnote("* Totals may be greater than the sum of categories due to activities outside of the SNU prioritization areas outlined above", notation = "number")

  cat('\n\n')
  cat('\\pagebreak')
  cat('\n\n')
  
```



```{r partner_table ,results='asis', echo=FALSE}

sub_heading<-names(d$partners)[3:length(d$partners)] %>% 
  stringr::str_split(.," ") %>% 
  purrr::map(purrr::pluck(2)) %>%
  unlist()

group_heading<-names(d$partners)[3:length(d$partners)] %>% 
  stringr::str_split(.," ") %>% 
  purrr::map(purrr::pluck(1)) %>% 
  unlist() %>% 
  factor(.,levels = unique(.)) %>%
  table(.)

```


```{r partner_table_1 ,results='asis', echo=FALSE}
#HTS_INDEX -> TX_PVLS
kable(d$partners[,c(1:14)], "latex", booktabs = T, 
      longtable=T,
      format.args = list(big.mark = ","),
      col.names = c("Funding Agency","Partner",sub_heading[1:12]), 
      caption = "HTS\\_INDEX to TX\\_PVLS") %>%
  kable_styling(font_size = 7) %>% 
  column_spec(1,width = "0.5in") %>% 
  column_spec(2,width = "1in") %>% 
  column_spec(3:14,width = "0.25in") %>% 
  add_header_above(c("","",group_heading[1:6])) %>% 
  row_spec(which(d$partners$Partner == ""),background = "lightgray")

 cat('\n\n')
  cat('\\pagebreak')
  cat('\n\n')
  
```


```{r partner_table_2 ,results='asis', echo=FALSE}
#CXCA_>PMTCT_EID
kable(d$partners[,c(1:2,15:25)], "latex", booktabs = T, longtable=T,format.args = list(big.mark = ","),
      col.names = c("Funding Agency","Partner",sub_heading[13:23]),
      caption = "CXCA\\_SCRN to PMTCT\\_EID" ) %>%
  kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% 
  column_spec(1,width = "0.5in") %>% 
  column_spec(2,width = "1in") %>% 
  column_spec(3:10,width = "0.25in") %>% 
  add_header_above(c("","",group_heading[7:13])) %>% 
  row_spec(which(d$partners$Partner == ""),background = "lightgray", )

 cat('\n\n')
  cat('\\pagebreak')
  cat('\n\n')
  
```


```{r partner_table_3 ,results='asis', echo=FALSE}  
#PP_PREV-> Prep_CURR
kable(d$partners[,c(1:2,26:34)], "latex", booktabs = T, longtable=T,format.args = list(big.mark = ","),
      col.names = c("Funding Agency","Partner",sub_heading[24:32]),
      caption = "PP\\_PREV to PrEP\\_CURR ") %>%
   kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% 
  column_spec(1,width = "0.5in") %>%
  column_spec(2,width = "1in") %>% 
  column_spec(3:10,width = "0.25in") %>% 
  add_header_above(c("","",group_heading[14:20])) %>% 
  row_spec(which(d$partners$Partner == ""),background = "lightgray")

 cat('\n\n')
  cat('\\pagebreak')
  cat('\n\n')
  
```
  
  
```{r partner_table_4  ,results='asis', echo=FALSE} 

  #TB_STAT->OVC_HIV_STAT
  kable(d$partners[,c(1:2,35:43)], "latex", booktabs = T, longtable=T,format.args = list(big.mark = ","),
      col.names = c("Funding Agency","Partner",sub_heading[33:41]),
      caption = "TB\\_STAT to GEND\\_GBV") %>%
   kable_styling(font_size = 7, latex_options = c("repeat_header")) %>% 
  column_spec(1,width = "0.5in") %>%
  column_spec(2,width = "1in") %>% 
  column_spec(3:10,width = "0.25in") %>% 
  add_header_above(c("","",group_heading[21:25])) %>% 
  row_spec(which(d$partners$Partner == ""),background = "lightgray")

 cat('\n\n')
  cat('\\pagebreak')
  cat('\n\n')
  
  
```



